### ISSUE TITLE
Change RSDK directory

### ISSUE THREAD

**Issue by Spider-Sonic** [Clownacy/Sonic-Mania-Decompilation-Wii-U#8]
Hello,
I want to make a WUP of this homebrew with the Data.rsdk in the WUP to make it more unified.
But I can't found the RSDK directory in your master. 
Is it possible to know where it is and if what I'm trying to do is possible?

Many regards,
Rayz0rum

**Comment by Clownacy** [comment]
Sorry, I misunderstood the problem you were having. To change where the game loads the `Data.rsdk` file from, you need to edit [this function](https://github.com/Clownacy/RSDKv5-Decompilation-Wii-U/blob/d42f507fd5e7a93ab5c645703e244a03921847c7/RSDKv5/RSDK/User/Core/UserStorage.cpp#L1150C6-L1150C34).
