### ISSUE TITLE
"Mod loading done"

### ISSUE THREAD

**Issue by XxQuexX** [Clownacy/Sonic-Mania-Decompilation-Wii-U#9]
Doubt this'll be seen but I guess I can hope, nothing lost in not trying
This issue goes to both opening the game through the homebrew channel (Tiramisu) or the Wii U Menu (Aroma) 
After opening the game (takes about 5-6 seconds on a black screen through HB channel, has a Sonic Mania splashscreen through Wii U Menu and might last a bit longer iirc), I'm met with nothing more than a black screen with a blue box written in the middle of it in white: "Mod loading done!" (the screen seems noticably darkened for some reason the white and blue are clearly unusually dark/shadowed)
From here on, nothing happens. I tried everything: Left/Right Stick, L/ZL/L3, R/ZR/R3, D-Pad, ABXY, Start/Select, tapping the screen, etc, and it stayed the exact same. I thought it just froze, but after pressing Home it just returns to the HB Channel/Wii U Pause Screen.
Did absolutely nobody run into the same issue??

**Comment by catod0** [comment]
so weird

so mods are used for pro controller support and some other things, but if you deactivate it from the settings.ini file you should be able to control sonic with the wii u gamepad (I guess).

I dont know if it'll work if you delete them from the mods folder but you could try either way.

and i guess you're one poor soul that got to that exact problem.

**Comment by catod0** [comment]
And don't you dare tell me you didn't put the Data.rsdk file in the rsdk folder

**Comment by RealyCoolWolf** [comment]
I'm having the same problem

**Comment by Clownacy** [comment]
And you definitely installed Data.rsdk to the right location?
